/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.heepay.manage.rpc.service;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-12-21")
public class AntifraudService {

  public interface Iface {

    public List<AntifraudThrift> getAntifraudInfoByMerchantId(List<String> merchantIds) throws org.apache.thrift.TException;

    public List<AntifraudThrift> getAntifraudInfoByLoginName(List<String> loginNames) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void getAntifraudInfoByMerchantId(List<String> merchantIds, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException;

    public void getAntifraudInfoByLoginName(List<String> loginNames, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public List<AntifraudThrift> getAntifraudInfoByMerchantId(List<String> merchantIds) throws org.apache.thrift.TException
    {
      send_getAntifraudInfoByMerchantId(merchantIds);
      return recv_getAntifraudInfoByMerchantId();
    }

    public void send_getAntifraudInfoByMerchantId(List<String> merchantIds) throws org.apache.thrift.TException
    {
      getAntifraudInfoByMerchantId_args args = new getAntifraudInfoByMerchantId_args();
      args.setMerchantIds(merchantIds);
      sendBase("getAntifraudInfoByMerchantId", args);
    }

    public List<AntifraudThrift> recv_getAntifraudInfoByMerchantId() throws org.apache.thrift.TException
    {
      getAntifraudInfoByMerchantId_result result = new getAntifraudInfoByMerchantId_result();
      receiveBase(result, "getAntifraudInfoByMerchantId");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "getAntifraudInfoByMerchantId failed: unknown result");
    }

    public List<AntifraudThrift> getAntifraudInfoByLoginName(List<String> loginNames) throws org.apache.thrift.TException
    {
      send_getAntifraudInfoByLoginName(loginNames);
      return recv_getAntifraudInfoByLoginName();
    }

    public void send_getAntifraudInfoByLoginName(List<String> loginNames) throws org.apache.thrift.TException
    {
      getAntifraudInfoByLoginName_args args = new getAntifraudInfoByLoginName_args();
      args.setLoginNames(loginNames);
      sendBase("getAntifraudInfoByLoginName", args);
    }

    public List<AntifraudThrift> recv_getAntifraudInfoByLoginName() throws org.apache.thrift.TException
    {
      getAntifraudInfoByLoginName_result result = new getAntifraudInfoByLoginName_result();
      receiveBase(result, "getAntifraudInfoByLoginName");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "getAntifraudInfoByLoginName failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void getAntifraudInfoByMerchantId(List<String> merchantIds, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException {
      checkReady();
      getAntifraudInfoByMerchantId_call method_call = new getAntifraudInfoByMerchantId_call(merchantIds, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class getAntifraudInfoByMerchantId_call extends org.apache.thrift.async.TAsyncMethodCall {
      private List<String> merchantIds;
      public getAntifraudInfoByMerchantId_call(List<String> merchantIds, org.apache.thrift.async.AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.merchantIds = merchantIds;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("getAntifraudInfoByMerchantId", org.apache.thrift.protocol.TMessageType.CALL, 0));
        getAntifraudInfoByMerchantId_args args = new getAntifraudInfoByMerchantId_args();
        args.setMerchantIds(merchantIds);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public List<AntifraudThrift> getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_getAntifraudInfoByMerchantId();
      }
    }

    public void getAntifraudInfoByLoginName(List<String> loginNames, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException {
      checkReady();
      getAntifraudInfoByLoginName_call method_call = new getAntifraudInfoByLoginName_call(loginNames, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class getAntifraudInfoByLoginName_call extends org.apache.thrift.async.TAsyncMethodCall {
      private List<String> loginNames;
      public getAntifraudInfoByLoginName_call(List<String> loginNames, org.apache.thrift.async.AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.loginNames = loginNames;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("getAntifraudInfoByLoginName", org.apache.thrift.protocol.TMessageType.CALL, 0));
        getAntifraudInfoByLoginName_args args = new getAntifraudInfoByLoginName_args();
        args.setLoginNames(loginNames);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public List<AntifraudThrift> getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_getAntifraudInfoByLoginName();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("getAntifraudInfoByMerchantId", new getAntifraudInfoByMerchantId());
      processMap.put("getAntifraudInfoByLoginName", new getAntifraudInfoByLoginName());
      return processMap;
    }

    public static class getAntifraudInfoByMerchantId<I extends Iface> extends org.apache.thrift.ProcessFunction<I, getAntifraudInfoByMerchantId_args> {
      public getAntifraudInfoByMerchantId() {
        super("getAntifraudInfoByMerchantId");
      }

      public getAntifraudInfoByMerchantId_args getEmptyArgsInstance() {
        return new getAntifraudInfoByMerchantId_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public getAntifraudInfoByMerchantId_result getResult(I iface, getAntifraudInfoByMerchantId_args args) throws org.apache.thrift.TException {
        getAntifraudInfoByMerchantId_result result = new getAntifraudInfoByMerchantId_result();
        result.success = iface.getAntifraudInfoByMerchantId(args.merchantIds);
        return result;
      }
    }

    public static class getAntifraudInfoByLoginName<I extends Iface> extends org.apache.thrift.ProcessFunction<I, getAntifraudInfoByLoginName_args> {
      public getAntifraudInfoByLoginName() {
        super("getAntifraudInfoByLoginName");
      }

      public getAntifraudInfoByLoginName_args getEmptyArgsInstance() {
        return new getAntifraudInfoByLoginName_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public getAntifraudInfoByLoginName_result getResult(I iface, getAntifraudInfoByLoginName_args args) throws org.apache.thrift.TException {
        getAntifraudInfoByLoginName_result result = new getAntifraudInfoByLoginName_result();
        result.success = iface.getAntifraudInfoByLoginName(args.loginNames);
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final Logger LOGGER = LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("getAntifraudInfoByMerchantId", new getAntifraudInfoByMerchantId());
      processMap.put("getAntifraudInfoByLoginName", new getAntifraudInfoByLoginName());
      return processMap;
    }

    public static class getAntifraudInfoByMerchantId<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, getAntifraudInfoByMerchantId_args, List<AntifraudThrift>> {
      public getAntifraudInfoByMerchantId() {
        super("getAntifraudInfoByMerchantId");
      }

      public getAntifraudInfoByMerchantId_args getEmptyArgsInstance() {
        return new getAntifraudInfoByMerchantId_args();
      }

      public AsyncMethodCallback<List<AntifraudThrift>> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<List<AntifraudThrift>>() { 
          public void onComplete(List<AntifraudThrift> o) {
            getAntifraudInfoByMerchantId_result result = new getAntifraudInfoByMerchantId_result();
            result.success = o;
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            getAntifraudInfoByMerchantId_result result = new getAntifraudInfoByMerchantId_result();
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, getAntifraudInfoByMerchantId_args args, org.apache.thrift.async.AsyncMethodCallback<List<AntifraudThrift>> resultHandler) throws TException {
        iface.getAntifraudInfoByMerchantId(args.merchantIds,resultHandler);
      }
    }

    public static class getAntifraudInfoByLoginName<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, getAntifraudInfoByLoginName_args, List<AntifraudThrift>> {
      public getAntifraudInfoByLoginName() {
        super("getAntifraudInfoByLoginName");
      }

      public getAntifraudInfoByLoginName_args getEmptyArgsInstance() {
        return new getAntifraudInfoByLoginName_args();
      }

      public AsyncMethodCallback<List<AntifraudThrift>> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<List<AntifraudThrift>>() { 
          public void onComplete(List<AntifraudThrift> o) {
            getAntifraudInfoByLoginName_result result = new getAntifraudInfoByLoginName_result();
            result.success = o;
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            getAntifraudInfoByLoginName_result result = new getAntifraudInfoByLoginName_result();
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, getAntifraudInfoByLoginName_args args, org.apache.thrift.async.AsyncMethodCallback<List<AntifraudThrift>> resultHandler) throws TException {
        iface.getAntifraudInfoByLoginName(args.loginNames,resultHandler);
      }
    }

  }

  public static class getAntifraudInfoByMerchantId_args implements org.apache.thrift.TBase<getAntifraudInfoByMerchantId_args, getAntifraudInfoByMerchantId_args._Fields>, java.io.Serializable, Cloneable, Comparable<getAntifraudInfoByMerchantId_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getAntifraudInfoByMerchantId_args");

    private static final org.apache.thrift.protocol.TField MERCHANT_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("merchantIds", org.apache.thrift.protocol.TType.LIST, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new getAntifraudInfoByMerchantId_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new getAntifraudInfoByMerchantId_argsTupleSchemeFactory());
    }

    public List<String> merchantIds; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      MERCHANT_IDS((short)1, "merchantIds");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // MERCHANT_IDS
            return MERCHANT_IDS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.MERCHANT_IDS, new org.apache.thrift.meta_data.FieldMetaData("merchantIds", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
              new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getAntifraudInfoByMerchantId_args.class, metaDataMap);
    }

    public getAntifraudInfoByMerchantId_args() {
    }

    public getAntifraudInfoByMerchantId_args(
      List<String> merchantIds)
    {
      this();
      this.merchantIds = merchantIds;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getAntifraudInfoByMerchantId_args(getAntifraudInfoByMerchantId_args other) {
      if (other.isSetMerchantIds()) {
        List<String> __this__merchantIds = new ArrayList<String>(other.merchantIds);
        this.merchantIds = __this__merchantIds;
      }
    }

    public getAntifraudInfoByMerchantId_args deepCopy() {
      return new getAntifraudInfoByMerchantId_args(this);
    }

    @Override
    public void clear() {
      this.merchantIds = null;
    }

    public int getMerchantIdsSize() {
      return (this.merchantIds == null) ? 0 : this.merchantIds.size();
    }

    public java.util.Iterator<String> getMerchantIdsIterator() {
      return (this.merchantIds == null) ? null : this.merchantIds.iterator();
    }

    public void addToMerchantIds(String elem) {
      if (this.merchantIds == null) {
        this.merchantIds = new ArrayList<String>();
      }
      this.merchantIds.add(elem);
    }

    public List<String> getMerchantIds() {
      return this.merchantIds;
    }

    public getAntifraudInfoByMerchantId_args setMerchantIds(List<String> merchantIds) {
      this.merchantIds = merchantIds;
      return this;
    }

    public void unsetMerchantIds() {
      this.merchantIds = null;
    }

    /** Returns true if field merchantIds is set (has been assigned a value) and false otherwise */
    public boolean isSetMerchantIds() {
      return this.merchantIds != null;
    }

    public void setMerchantIdsIsSet(boolean value) {
      if (!value) {
        this.merchantIds = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case MERCHANT_IDS:
        if (value == null) {
          unsetMerchantIds();
        } else {
          setMerchantIds((List<String>)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case MERCHANT_IDS:
        return getMerchantIds();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case MERCHANT_IDS:
        return isSetMerchantIds();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getAntifraudInfoByMerchantId_args)
        return this.equals((getAntifraudInfoByMerchantId_args)that);
      return false;
    }

    public boolean equals(getAntifraudInfoByMerchantId_args that) {
      if (that == null)
        return false;

      boolean this_present_merchantIds = true && this.isSetMerchantIds();
      boolean that_present_merchantIds = true && that.isSetMerchantIds();
      if (this_present_merchantIds || that_present_merchantIds) {
        if (!(this_present_merchantIds && that_present_merchantIds))
          return false;
        if (!this.merchantIds.equals(that.merchantIds))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_merchantIds = true && (isSetMerchantIds());
      list.add(present_merchantIds);
      if (present_merchantIds)
        list.add(merchantIds);

      return list.hashCode();
    }

    @Override
    public int compareTo(getAntifraudInfoByMerchantId_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetMerchantIds()).compareTo(other.isSetMerchantIds());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetMerchantIds()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.merchantIds, other.merchantIds);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getAntifraudInfoByMerchantId_args(");
      boolean first = true;

      sb.append("merchantIds:");
      if (this.merchantIds == null) {
        sb.append("null");
      } else {
        sb.append(this.merchantIds);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getAntifraudInfoByMerchantId_argsStandardSchemeFactory implements SchemeFactory {
      public getAntifraudInfoByMerchantId_argsStandardScheme getScheme() {
        return new getAntifraudInfoByMerchantId_argsStandardScheme();
      }
    }

    private static class getAntifraudInfoByMerchantId_argsStandardScheme extends StandardScheme<getAntifraudInfoByMerchantId_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getAntifraudInfoByMerchantId_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // MERCHANT_IDS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                  struct.merchantIds = new ArrayList<String>(_list0.size);
                  String _elem1;
                  for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                  {
                    _elem1 = iprot.readString();
                    struct.merchantIds.add(_elem1);
                  }
                  iprot.readListEnd();
                }
                struct.setMerchantIdsIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getAntifraudInfoByMerchantId_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.merchantIds != null) {
          oprot.writeFieldBegin(MERCHANT_IDS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.merchantIds.size()));
            for (String _iter3 : struct.merchantIds)
            {
              oprot.writeString(_iter3);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getAntifraudInfoByMerchantId_argsTupleSchemeFactory implements SchemeFactory {
      public getAntifraudInfoByMerchantId_argsTupleScheme getScheme() {
        return new getAntifraudInfoByMerchantId_argsTupleScheme();
      }
    }

    private static class getAntifraudInfoByMerchantId_argsTupleScheme extends TupleScheme<getAntifraudInfoByMerchantId_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getAntifraudInfoByMerchantId_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetMerchantIds()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetMerchantIds()) {
          {
            oprot.writeI32(struct.merchantIds.size());
            for (String _iter4 : struct.merchantIds)
            {
              oprot.writeString(_iter4);
            }
          }
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getAntifraudInfoByMerchantId_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          {
            org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
            struct.merchantIds = new ArrayList<String>(_list5.size);
            String _elem6;
            for (int _i7 = 0; _i7 < _list5.size; ++_i7)
            {
              _elem6 = iprot.readString();
              struct.merchantIds.add(_elem6);
            }
          }
          struct.setMerchantIdsIsSet(true);
        }
      }
    }

  }

  public static class getAntifraudInfoByMerchantId_result implements org.apache.thrift.TBase<getAntifraudInfoByMerchantId_result, getAntifraudInfoByMerchantId_result._Fields>, java.io.Serializable, Cloneable, Comparable<getAntifraudInfoByMerchantId_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getAntifraudInfoByMerchantId_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.LIST, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new getAntifraudInfoByMerchantId_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new getAntifraudInfoByMerchantId_resultTupleSchemeFactory());
    }

    public List<AntifraudThrift> success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
              new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, AntifraudThrift.class))));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getAntifraudInfoByMerchantId_result.class, metaDataMap);
    }

    public getAntifraudInfoByMerchantId_result() {
    }

    public getAntifraudInfoByMerchantId_result(
      List<AntifraudThrift> success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getAntifraudInfoByMerchantId_result(getAntifraudInfoByMerchantId_result other) {
      if (other.isSetSuccess()) {
        List<AntifraudThrift> __this__success = new ArrayList<AntifraudThrift>(other.success.size());
        for (AntifraudThrift other_element : other.success) {
          __this__success.add(new AntifraudThrift(other_element));
        }
        this.success = __this__success;
      }
    }

    public getAntifraudInfoByMerchantId_result deepCopy() {
      return new getAntifraudInfoByMerchantId_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public int getSuccessSize() {
      return (this.success == null) ? 0 : this.success.size();
    }

    public java.util.Iterator<AntifraudThrift> getSuccessIterator() {
      return (this.success == null) ? null : this.success.iterator();
    }

    public void addToSuccess(AntifraudThrift elem) {
      if (this.success == null) {
        this.success = new ArrayList<AntifraudThrift>();
      }
      this.success.add(elem);
    }

    public List<AntifraudThrift> getSuccess() {
      return this.success;
    }

    public getAntifraudInfoByMerchantId_result setSuccess(List<AntifraudThrift> success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((List<AntifraudThrift>)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getAntifraudInfoByMerchantId_result)
        return this.equals((getAntifraudInfoByMerchantId_result)that);
      return false;
    }

    public boolean equals(getAntifraudInfoByMerchantId_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_success = true && (isSetSuccess());
      list.add(present_success);
      if (present_success)
        list.add(success);

      return list.hashCode();
    }

    @Override
    public int compareTo(getAntifraudInfoByMerchantId_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getAntifraudInfoByMerchantId_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getAntifraudInfoByMerchantId_resultStandardSchemeFactory implements SchemeFactory {
      public getAntifraudInfoByMerchantId_resultStandardScheme getScheme() {
        return new getAntifraudInfoByMerchantId_resultStandardScheme();
      }
    }

    private static class getAntifraudInfoByMerchantId_resultStandardScheme extends StandardScheme<getAntifraudInfoByMerchantId_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getAntifraudInfoByMerchantId_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                  struct.success = new ArrayList<AntifraudThrift>(_list8.size);
                  AntifraudThrift _elem9;
                  for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                  {
                    _elem9 = new AntifraudThrift();
                    _elem9.read(iprot);
                    struct.success.add(_elem9);
                  }
                  iprot.readListEnd();
                }
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getAntifraudInfoByMerchantId_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.success.size()));
            for (AntifraudThrift _iter11 : struct.success)
            {
              _iter11.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getAntifraudInfoByMerchantId_resultTupleSchemeFactory implements SchemeFactory {
      public getAntifraudInfoByMerchantId_resultTupleScheme getScheme() {
        return new getAntifraudInfoByMerchantId_resultTupleScheme();
      }
    }

    private static class getAntifraudInfoByMerchantId_resultTupleScheme extends TupleScheme<getAntifraudInfoByMerchantId_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getAntifraudInfoByMerchantId_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          {
            oprot.writeI32(struct.success.size());
            for (AntifraudThrift _iter12 : struct.success)
            {
              _iter12.write(oprot);
            }
          }
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getAntifraudInfoByMerchantId_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          {
            org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
            struct.success = new ArrayList<AntifraudThrift>(_list13.size);
            AntifraudThrift _elem14;
            for (int _i15 = 0; _i15 < _list13.size; ++_i15)
            {
              _elem14 = new AntifraudThrift();
              _elem14.read(iprot);
              struct.success.add(_elem14);
            }
          }
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

  public static class getAntifraudInfoByLoginName_args implements org.apache.thrift.TBase<getAntifraudInfoByLoginName_args, getAntifraudInfoByLoginName_args._Fields>, java.io.Serializable, Cloneable, Comparable<getAntifraudInfoByLoginName_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getAntifraudInfoByLoginName_args");

    private static final org.apache.thrift.protocol.TField LOGIN_NAMES_FIELD_DESC = new org.apache.thrift.protocol.TField("loginNames", org.apache.thrift.protocol.TType.LIST, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new getAntifraudInfoByLoginName_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new getAntifraudInfoByLoginName_argsTupleSchemeFactory());
    }

    public List<String> loginNames; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      LOGIN_NAMES((short)1, "loginNames");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // LOGIN_NAMES
            return LOGIN_NAMES;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.LOGIN_NAMES, new org.apache.thrift.meta_data.FieldMetaData("loginNames", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
              new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getAntifraudInfoByLoginName_args.class, metaDataMap);
    }

    public getAntifraudInfoByLoginName_args() {
    }

    public getAntifraudInfoByLoginName_args(
      List<String> loginNames)
    {
      this();
      this.loginNames = loginNames;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getAntifraudInfoByLoginName_args(getAntifraudInfoByLoginName_args other) {
      if (other.isSetLoginNames()) {
        List<String> __this__loginNames = new ArrayList<String>(other.loginNames);
        this.loginNames = __this__loginNames;
      }
    }

    public getAntifraudInfoByLoginName_args deepCopy() {
      return new getAntifraudInfoByLoginName_args(this);
    }

    @Override
    public void clear() {
      this.loginNames = null;
    }

    public int getLoginNamesSize() {
      return (this.loginNames == null) ? 0 : this.loginNames.size();
    }

    public java.util.Iterator<String> getLoginNamesIterator() {
      return (this.loginNames == null) ? null : this.loginNames.iterator();
    }

    public void addToLoginNames(String elem) {
      if (this.loginNames == null) {
        this.loginNames = new ArrayList<String>();
      }
      this.loginNames.add(elem);
    }

    public List<String> getLoginNames() {
      return this.loginNames;
    }

    public getAntifraudInfoByLoginName_args setLoginNames(List<String> loginNames) {
      this.loginNames = loginNames;
      return this;
    }

    public void unsetLoginNames() {
      this.loginNames = null;
    }

    /** Returns true if field loginNames is set (has been assigned a value) and false otherwise */
    public boolean isSetLoginNames() {
      return this.loginNames != null;
    }

    public void setLoginNamesIsSet(boolean value) {
      if (!value) {
        this.loginNames = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case LOGIN_NAMES:
        if (value == null) {
          unsetLoginNames();
        } else {
          setLoginNames((List<String>)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case LOGIN_NAMES:
        return getLoginNames();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case LOGIN_NAMES:
        return isSetLoginNames();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getAntifraudInfoByLoginName_args)
        return this.equals((getAntifraudInfoByLoginName_args)that);
      return false;
    }

    public boolean equals(getAntifraudInfoByLoginName_args that) {
      if (that == null)
        return false;

      boolean this_present_loginNames = true && this.isSetLoginNames();
      boolean that_present_loginNames = true && that.isSetLoginNames();
      if (this_present_loginNames || that_present_loginNames) {
        if (!(this_present_loginNames && that_present_loginNames))
          return false;
        if (!this.loginNames.equals(that.loginNames))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_loginNames = true && (isSetLoginNames());
      list.add(present_loginNames);
      if (present_loginNames)
        list.add(loginNames);

      return list.hashCode();
    }

    @Override
    public int compareTo(getAntifraudInfoByLoginName_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetLoginNames()).compareTo(other.isSetLoginNames());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetLoginNames()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.loginNames, other.loginNames);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getAntifraudInfoByLoginName_args(");
      boolean first = true;

      sb.append("loginNames:");
      if (this.loginNames == null) {
        sb.append("null");
      } else {
        sb.append(this.loginNames);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getAntifraudInfoByLoginName_argsStandardSchemeFactory implements SchemeFactory {
      public getAntifraudInfoByLoginName_argsStandardScheme getScheme() {
        return new getAntifraudInfoByLoginName_argsStandardScheme();
      }
    }

    private static class getAntifraudInfoByLoginName_argsStandardScheme extends StandardScheme<getAntifraudInfoByLoginName_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getAntifraudInfoByLoginName_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // LOGIN_NAMES
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list16 = iprot.readListBegin();
                  struct.loginNames = new ArrayList<String>(_list16.size);
                  String _elem17;
                  for (int _i18 = 0; _i18 < _list16.size; ++_i18)
                  {
                    _elem17 = iprot.readString();
                    struct.loginNames.add(_elem17);
                  }
                  iprot.readListEnd();
                }
                struct.setLoginNamesIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getAntifraudInfoByLoginName_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.loginNames != null) {
          oprot.writeFieldBegin(LOGIN_NAMES_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.loginNames.size()));
            for (String _iter19 : struct.loginNames)
            {
              oprot.writeString(_iter19);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getAntifraudInfoByLoginName_argsTupleSchemeFactory implements SchemeFactory {
      public getAntifraudInfoByLoginName_argsTupleScheme getScheme() {
        return new getAntifraudInfoByLoginName_argsTupleScheme();
      }
    }

    private static class getAntifraudInfoByLoginName_argsTupleScheme extends TupleScheme<getAntifraudInfoByLoginName_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getAntifraudInfoByLoginName_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetLoginNames()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetLoginNames()) {
          {
            oprot.writeI32(struct.loginNames.size());
            for (String _iter20 : struct.loginNames)
            {
              oprot.writeString(_iter20);
            }
          }
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getAntifraudInfoByLoginName_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          {
            org.apache.thrift.protocol.TList _list21 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
            struct.loginNames = new ArrayList<String>(_list21.size);
            String _elem22;
            for (int _i23 = 0; _i23 < _list21.size; ++_i23)
            {
              _elem22 = iprot.readString();
              struct.loginNames.add(_elem22);
            }
          }
          struct.setLoginNamesIsSet(true);
        }
      }
    }

  }

  public static class getAntifraudInfoByLoginName_result implements org.apache.thrift.TBase<getAntifraudInfoByLoginName_result, getAntifraudInfoByLoginName_result._Fields>, java.io.Serializable, Cloneable, Comparable<getAntifraudInfoByLoginName_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getAntifraudInfoByLoginName_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.LIST, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new getAntifraudInfoByLoginName_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new getAntifraudInfoByLoginName_resultTupleSchemeFactory());
    }

    public List<AntifraudThrift> success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
              new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, AntifraudThrift.class))));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getAntifraudInfoByLoginName_result.class, metaDataMap);
    }

    public getAntifraudInfoByLoginName_result() {
    }

    public getAntifraudInfoByLoginName_result(
      List<AntifraudThrift> success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getAntifraudInfoByLoginName_result(getAntifraudInfoByLoginName_result other) {
      if (other.isSetSuccess()) {
        List<AntifraudThrift> __this__success = new ArrayList<AntifraudThrift>(other.success.size());
        for (AntifraudThrift other_element : other.success) {
          __this__success.add(new AntifraudThrift(other_element));
        }
        this.success = __this__success;
      }
    }

    public getAntifraudInfoByLoginName_result deepCopy() {
      return new getAntifraudInfoByLoginName_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public int getSuccessSize() {
      return (this.success == null) ? 0 : this.success.size();
    }

    public java.util.Iterator<AntifraudThrift> getSuccessIterator() {
      return (this.success == null) ? null : this.success.iterator();
    }

    public void addToSuccess(AntifraudThrift elem) {
      if (this.success == null) {
        this.success = new ArrayList<AntifraudThrift>();
      }
      this.success.add(elem);
    }

    public List<AntifraudThrift> getSuccess() {
      return this.success;
    }

    public getAntifraudInfoByLoginName_result setSuccess(List<AntifraudThrift> success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((List<AntifraudThrift>)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getAntifraudInfoByLoginName_result)
        return this.equals((getAntifraudInfoByLoginName_result)that);
      return false;
    }

    public boolean equals(getAntifraudInfoByLoginName_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_success = true && (isSetSuccess());
      list.add(present_success);
      if (present_success)
        list.add(success);

      return list.hashCode();
    }

    @Override
    public int compareTo(getAntifraudInfoByLoginName_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getAntifraudInfoByLoginName_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getAntifraudInfoByLoginName_resultStandardSchemeFactory implements SchemeFactory {
      public getAntifraudInfoByLoginName_resultStandardScheme getScheme() {
        return new getAntifraudInfoByLoginName_resultStandardScheme();
      }
    }

    private static class getAntifraudInfoByLoginName_resultStandardScheme extends StandardScheme<getAntifraudInfoByLoginName_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getAntifraudInfoByLoginName_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list24 = iprot.readListBegin();
                  struct.success = new ArrayList<AntifraudThrift>(_list24.size);
                  AntifraudThrift _elem25;
                  for (int _i26 = 0; _i26 < _list24.size; ++_i26)
                  {
                    _elem25 = new AntifraudThrift();
                    _elem25.read(iprot);
                    struct.success.add(_elem25);
                  }
                  iprot.readListEnd();
                }
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getAntifraudInfoByLoginName_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.success.size()));
            for (AntifraudThrift _iter27 : struct.success)
            {
              _iter27.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getAntifraudInfoByLoginName_resultTupleSchemeFactory implements SchemeFactory {
      public getAntifraudInfoByLoginName_resultTupleScheme getScheme() {
        return new getAntifraudInfoByLoginName_resultTupleScheme();
      }
    }

    private static class getAntifraudInfoByLoginName_resultTupleScheme extends TupleScheme<getAntifraudInfoByLoginName_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getAntifraudInfoByLoginName_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          {
            oprot.writeI32(struct.success.size());
            for (AntifraudThrift _iter28 : struct.success)
            {
              _iter28.write(oprot);
            }
          }
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getAntifraudInfoByLoginName_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          {
            org.apache.thrift.protocol.TList _list29 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
            struct.success = new ArrayList<AntifraudThrift>(_list29.size);
            AntifraudThrift _elem30;
            for (int _i31 = 0; _i31 < _list29.size; ++_i31)
            {
              _elem30 = new AntifraudThrift();
              _elem30.read(iprot);
              struct.success.add(_elem30);
            }
          }
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

}
