/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.heepay.rpc.billing.model;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-11-11")
public class ClearShareProfitDetailModel implements org.apache.thrift.TBase<ClearShareProfitDetailModel, ClearShareProfitDetailModel._Fields>, java.io.Serializable, Cloneable, Comparable<ClearShareProfitDetailModel> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ClearShareProfitDetailModel");

  private static final org.apache.thrift.protocol.TField MERCHANT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("merchantId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField TRANS_NO_FIELD_DESC = new org.apache.thrift.protocol.TField("transNo", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PROFIT_AMOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("profitAmount", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField TRANS_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("transType", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField SHARE_DETAIL_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("shareDetailId", org.apache.thrift.protocol.TType.STRING, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ClearShareProfitDetailModelStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ClearShareProfitDetailModelTupleSchemeFactory());
  }

  public String merchantId; // required
  public String transNo; // required
  public String profitAmount; // required
  public String transType; // required
  public String shareDetailId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MERCHANT_ID((short)1, "merchantId"),
    TRANS_NO((short)2, "transNo"),
    PROFIT_AMOUNT((short)3, "profitAmount"),
    TRANS_TYPE((short)4, "transType"),
    SHARE_DETAIL_ID((short)5, "shareDetailId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MERCHANT_ID
          return MERCHANT_ID;
        case 2: // TRANS_NO
          return TRANS_NO;
        case 3: // PROFIT_AMOUNT
          return PROFIT_AMOUNT;
        case 4: // TRANS_TYPE
          return TRANS_TYPE;
        case 5: // SHARE_DETAIL_ID
          return SHARE_DETAIL_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MERCHANT_ID, new org.apache.thrift.meta_data.FieldMetaData("merchantId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TRANS_NO, new org.apache.thrift.meta_data.FieldMetaData("transNo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PROFIT_AMOUNT, new org.apache.thrift.meta_data.FieldMetaData("profitAmount", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TRANS_TYPE, new org.apache.thrift.meta_data.FieldMetaData("transType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SHARE_DETAIL_ID, new org.apache.thrift.meta_data.FieldMetaData("shareDetailId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ClearShareProfitDetailModel.class, metaDataMap);
  }

  public ClearShareProfitDetailModel() {
  }

  public ClearShareProfitDetailModel(
    String merchantId,
    String transNo,
    String profitAmount,
    String transType,
    String shareDetailId)
  {
    this();
    this.merchantId = merchantId;
    this.transNo = transNo;
    this.profitAmount = profitAmount;
    this.transType = transType;
    this.shareDetailId = shareDetailId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ClearShareProfitDetailModel(ClearShareProfitDetailModel other) {
    if (other.isSetMerchantId()) {
      this.merchantId = other.merchantId;
    }
    if (other.isSetTransNo()) {
      this.transNo = other.transNo;
    }
    if (other.isSetProfitAmount()) {
      this.profitAmount = other.profitAmount;
    }
    if (other.isSetTransType()) {
      this.transType = other.transType;
    }
    if (other.isSetShareDetailId()) {
      this.shareDetailId = other.shareDetailId;
    }
  }

  public ClearShareProfitDetailModel deepCopy() {
    return new ClearShareProfitDetailModel(this);
  }

  @Override
  public void clear() {
    this.merchantId = null;
    this.transNo = null;
    this.profitAmount = null;
    this.transType = null;
    this.shareDetailId = null;
  }

  public String getMerchantId() {
    return this.merchantId;
  }

  public ClearShareProfitDetailModel setMerchantId(String merchantId) {
    this.merchantId = merchantId;
    return this;
  }

  public void unsetMerchantId() {
    this.merchantId = null;
  }

  /** Returns true if field merchantId is set (has been assigned a value) and false otherwise */
  public boolean isSetMerchantId() {
    return this.merchantId != null;
  }

  public void setMerchantIdIsSet(boolean value) {
    if (!value) {
      this.merchantId = null;
    }
  }

  public String getTransNo() {
    return this.transNo;
  }

  public ClearShareProfitDetailModel setTransNo(String transNo) {
    this.transNo = transNo;
    return this;
  }

  public void unsetTransNo() {
    this.transNo = null;
  }

  /** Returns true if field transNo is set (has been assigned a value) and false otherwise */
  public boolean isSetTransNo() {
    return this.transNo != null;
  }

  public void setTransNoIsSet(boolean value) {
    if (!value) {
      this.transNo = null;
    }
  }

  public String getProfitAmount() {
    return this.profitAmount;
  }

  public ClearShareProfitDetailModel setProfitAmount(String profitAmount) {
    this.profitAmount = profitAmount;
    return this;
  }

  public void unsetProfitAmount() {
    this.profitAmount = null;
  }

  /** Returns true if field profitAmount is set (has been assigned a value) and false otherwise */
  public boolean isSetProfitAmount() {
    return this.profitAmount != null;
  }

  public void setProfitAmountIsSet(boolean value) {
    if (!value) {
      this.profitAmount = null;
    }
  }

  public String getTransType() {
    return this.transType;
  }

  public ClearShareProfitDetailModel setTransType(String transType) {
    this.transType = transType;
    return this;
  }

  public void unsetTransType() {
    this.transType = null;
  }

  /** Returns true if field transType is set (has been assigned a value) and false otherwise */
  public boolean isSetTransType() {
    return this.transType != null;
  }

  public void setTransTypeIsSet(boolean value) {
    if (!value) {
      this.transType = null;
    }
  }

  public String getShareDetailId() {
    return this.shareDetailId;
  }

  public ClearShareProfitDetailModel setShareDetailId(String shareDetailId) {
    this.shareDetailId = shareDetailId;
    return this;
  }

  public void unsetShareDetailId() {
    this.shareDetailId = null;
  }

  /** Returns true if field shareDetailId is set (has been assigned a value) and false otherwise */
  public boolean isSetShareDetailId() {
    return this.shareDetailId != null;
  }

  public void setShareDetailIdIsSet(boolean value) {
    if (!value) {
      this.shareDetailId = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MERCHANT_ID:
      if (value == null) {
        unsetMerchantId();
      } else {
        setMerchantId((String)value);
      }
      break;

    case TRANS_NO:
      if (value == null) {
        unsetTransNo();
      } else {
        setTransNo((String)value);
      }
      break;

    case PROFIT_AMOUNT:
      if (value == null) {
        unsetProfitAmount();
      } else {
        setProfitAmount((String)value);
      }
      break;

    case TRANS_TYPE:
      if (value == null) {
        unsetTransType();
      } else {
        setTransType((String)value);
      }
      break;

    case SHARE_DETAIL_ID:
      if (value == null) {
        unsetShareDetailId();
      } else {
        setShareDetailId((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MERCHANT_ID:
      return getMerchantId();

    case TRANS_NO:
      return getTransNo();

    case PROFIT_AMOUNT:
      return getProfitAmount();

    case TRANS_TYPE:
      return getTransType();

    case SHARE_DETAIL_ID:
      return getShareDetailId();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MERCHANT_ID:
      return isSetMerchantId();
    case TRANS_NO:
      return isSetTransNo();
    case PROFIT_AMOUNT:
      return isSetProfitAmount();
    case TRANS_TYPE:
      return isSetTransType();
    case SHARE_DETAIL_ID:
      return isSetShareDetailId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ClearShareProfitDetailModel)
      return this.equals((ClearShareProfitDetailModel)that);
    return false;
  }

  public boolean equals(ClearShareProfitDetailModel that) {
    if (that == null)
      return false;

    boolean this_present_merchantId = true && this.isSetMerchantId();
    boolean that_present_merchantId = true && that.isSetMerchantId();
    if (this_present_merchantId || that_present_merchantId) {
      if (!(this_present_merchantId && that_present_merchantId))
        return false;
      if (!this.merchantId.equals(that.merchantId))
        return false;
    }

    boolean this_present_transNo = true && this.isSetTransNo();
    boolean that_present_transNo = true && that.isSetTransNo();
    if (this_present_transNo || that_present_transNo) {
      if (!(this_present_transNo && that_present_transNo))
        return false;
      if (!this.transNo.equals(that.transNo))
        return false;
    }

    boolean this_present_profitAmount = true && this.isSetProfitAmount();
    boolean that_present_profitAmount = true && that.isSetProfitAmount();
    if (this_present_profitAmount || that_present_profitAmount) {
      if (!(this_present_profitAmount && that_present_profitAmount))
        return false;
      if (!this.profitAmount.equals(that.profitAmount))
        return false;
    }

    boolean this_present_transType = true && this.isSetTransType();
    boolean that_present_transType = true && that.isSetTransType();
    if (this_present_transType || that_present_transType) {
      if (!(this_present_transType && that_present_transType))
        return false;
      if (!this.transType.equals(that.transType))
        return false;
    }

    boolean this_present_shareDetailId = true && this.isSetShareDetailId();
    boolean that_present_shareDetailId = true && that.isSetShareDetailId();
    if (this_present_shareDetailId || that_present_shareDetailId) {
      if (!(this_present_shareDetailId && that_present_shareDetailId))
        return false;
      if (!this.shareDetailId.equals(that.shareDetailId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_merchantId = true && (isSetMerchantId());
    list.add(present_merchantId);
    if (present_merchantId)
      list.add(merchantId);

    boolean present_transNo = true && (isSetTransNo());
    list.add(present_transNo);
    if (present_transNo)
      list.add(transNo);

    boolean present_profitAmount = true && (isSetProfitAmount());
    list.add(present_profitAmount);
    if (present_profitAmount)
      list.add(profitAmount);

    boolean present_transType = true && (isSetTransType());
    list.add(present_transType);
    if (present_transType)
      list.add(transType);

    boolean present_shareDetailId = true && (isSetShareDetailId());
    list.add(present_shareDetailId);
    if (present_shareDetailId)
      list.add(shareDetailId);

    return list.hashCode();
  }

  @Override
  public int compareTo(ClearShareProfitDetailModel other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMerchantId()).compareTo(other.isSetMerchantId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMerchantId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.merchantId, other.merchantId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTransNo()).compareTo(other.isSetTransNo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTransNo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.transNo, other.transNo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProfitAmount()).compareTo(other.isSetProfitAmount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProfitAmount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.profitAmount, other.profitAmount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTransType()).compareTo(other.isSetTransType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTransType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.transType, other.transType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetShareDetailId()).compareTo(other.isSetShareDetailId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetShareDetailId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.shareDetailId, other.shareDetailId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ClearShareProfitDetailModel(");
    boolean first = true;

    sb.append("merchantId:");
    if (this.merchantId == null) {
      sb.append("null");
    } else {
      sb.append(this.merchantId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("transNo:");
    if (this.transNo == null) {
      sb.append("null");
    } else {
      sb.append(this.transNo);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("profitAmount:");
    if (this.profitAmount == null) {
      sb.append("null");
    } else {
      sb.append(this.profitAmount);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("transType:");
    if (this.transType == null) {
      sb.append("null");
    } else {
      sb.append(this.transType);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("shareDetailId:");
    if (this.shareDetailId == null) {
      sb.append("null");
    } else {
      sb.append(this.shareDetailId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ClearShareProfitDetailModelStandardSchemeFactory implements SchemeFactory {
    public ClearShareProfitDetailModelStandardScheme getScheme() {
      return new ClearShareProfitDetailModelStandardScheme();
    }
  }

  private static class ClearShareProfitDetailModelStandardScheme extends StandardScheme<ClearShareProfitDetailModel> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ClearShareProfitDetailModel struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MERCHANT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.merchantId = iprot.readString();
              struct.setMerchantIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TRANS_NO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.transNo = iprot.readString();
              struct.setTransNoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PROFIT_AMOUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.profitAmount = iprot.readString();
              struct.setProfitAmountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // TRANS_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.transType = iprot.readString();
              struct.setTransTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // SHARE_DETAIL_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.shareDetailId = iprot.readString();
              struct.setShareDetailIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ClearShareProfitDetailModel struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.merchantId != null) {
        oprot.writeFieldBegin(MERCHANT_ID_FIELD_DESC);
        oprot.writeString(struct.merchantId);
        oprot.writeFieldEnd();
      }
      if (struct.transNo != null) {
        oprot.writeFieldBegin(TRANS_NO_FIELD_DESC);
        oprot.writeString(struct.transNo);
        oprot.writeFieldEnd();
      }
      if (struct.profitAmount != null) {
        oprot.writeFieldBegin(PROFIT_AMOUNT_FIELD_DESC);
        oprot.writeString(struct.profitAmount);
        oprot.writeFieldEnd();
      }
      if (struct.transType != null) {
        oprot.writeFieldBegin(TRANS_TYPE_FIELD_DESC);
        oprot.writeString(struct.transType);
        oprot.writeFieldEnd();
      }
      if (struct.shareDetailId != null) {
        oprot.writeFieldBegin(SHARE_DETAIL_ID_FIELD_DESC);
        oprot.writeString(struct.shareDetailId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ClearShareProfitDetailModelTupleSchemeFactory implements SchemeFactory {
    public ClearShareProfitDetailModelTupleScheme getScheme() {
      return new ClearShareProfitDetailModelTupleScheme();
    }
  }

  private static class ClearShareProfitDetailModelTupleScheme extends TupleScheme<ClearShareProfitDetailModel> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ClearShareProfitDetailModel struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMerchantId()) {
        optionals.set(0);
      }
      if (struct.isSetTransNo()) {
        optionals.set(1);
      }
      if (struct.isSetProfitAmount()) {
        optionals.set(2);
      }
      if (struct.isSetTransType()) {
        optionals.set(3);
      }
      if (struct.isSetShareDetailId()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetMerchantId()) {
        oprot.writeString(struct.merchantId);
      }
      if (struct.isSetTransNo()) {
        oprot.writeString(struct.transNo);
      }
      if (struct.isSetProfitAmount()) {
        oprot.writeString(struct.profitAmount);
      }
      if (struct.isSetTransType()) {
        oprot.writeString(struct.transType);
      }
      if (struct.isSetShareDetailId()) {
        oprot.writeString(struct.shareDetailId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ClearShareProfitDetailModel struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.merchantId = iprot.readString();
        struct.setMerchantIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.transNo = iprot.readString();
        struct.setTransNoIsSet(true);
      }
      if (incoming.get(2)) {
        struct.profitAmount = iprot.readString();
        struct.setProfitAmountIsSet(true);
      }
      if (incoming.get(3)) {
        struct.transType = iprot.readString();
        struct.setTransTypeIsSet(true);
      }
      if (incoming.get(4)) {
        struct.shareDetailId = iprot.readString();
        struct.setShareDetailIdIsSet(true);
      }
    }
  }

}

