package com.heepay.billing.dao;

import java.util.List;
import java.util.Map;
import java.util.Date;

import org.apache.ibatis.annotations.Param;

import com.heepay.billing.entity.SettleMerchantRecord;
import com.heepay.billing.entity.SettleMerchantRecordExample;

public interface SettleMerchantRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_merchant_record
     *
     * @mbggenerated Thu Sep 08 21:07:07 CST 2016
     */
    int countByExample(SettleMerchantRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_merchant_record
     *
     * @mbggenerated Thu Sep 08 21:07:07 CST 2016
     */
    int deleteByExample(SettleMerchantRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_merchant_record
     *
     * @mbggenerated Thu Sep 08 21:07:07 CST 2016
     */
    int deleteByPrimaryKey(Long settleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_merchant_record
     *
     * @mbggenerated Thu Sep 08 21:07:07 CST 2016
     */
    int insert(SettleMerchantRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_merchant_record
     *
     * @mbggenerated Thu Sep 08 21:07:07 CST 2016
     */
    int insertSelective(SettleMerchantRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_merchant_record
     *
     * @mbggenerated Thu Sep 08 21:07:07 CST 2016
     */
    List<SettleMerchantRecord> selectByExample(SettleMerchantRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_merchant_record
     *
     * @mbggenerated Thu Sep 08 21:07:07 CST 2016
     */
    SettleMerchantRecord selectByPrimaryKey(Long settleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_merchant_record
     *
     * @mbggenerated Thu Sep 08 21:07:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") SettleMerchantRecord record, @Param("example") SettleMerchantRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_merchant_record
     *
     * @mbggenerated Thu Sep 08 21:07:07 CST 2016
     */
    int updateByExample(@Param("record") SettleMerchantRecord record, @Param("example") SettleMerchantRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_merchant_record
     *
     * @mbggenerated Thu Sep 08 21:07:07 CST 2016
     */
    int updateByPrimaryKeySelective(SettleMerchantRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_merchant_record
     *
     * @mbggenerated Thu Sep 08 21:07:07 CST 2016
     */
    int updateByPrimaryKey(SettleMerchantRecord record);

    //修改用户侧结算表的状态
   	void updateMerchantStatus(SettleMerchantRecord record);
   	
   	
   	//修改结算表的状态
   	void batchUpdateMerchantStatus(SettleMerchantRecord record);
   
   	//汇总用户侧结算表   	
   	public List<Map> Summarizing(Date date);
   	
   	//查询结算表
   	public List<SettleMerchantRecord> querySettleMerchantDetail(Date checkDate, String productCode, String settleStatus, String checkStatus);
   	
   	//通过结算批次查询结算表
   	public SettleMerchantRecord querySettleMerchantByBatchNo(String batchNo);
   	
   	
	/**
	 * 更新结算表状态
	 * @param record
	 */
	public void updateSettleMerchantByBathcNo(SettleMerchantRecord record);

	void upateByFeeWay(SettleMerchantRecord record);

	List<SettleMerchantRecord> getSettleMerchantRecordByStatus(String checkStatus,String settleStatus,String date);
	
	/**
	 * 
	 * @方法说明：
	 * @author xuangang
	 * @param settleStatus 已结算
	 * @param settleDate 结算日期
	 * @return
	 * @时间：2017年3月14日下午3:15:29
	 */
	public List<SettleMerchantRecord> queryAgentforSettle(String settleStatus, Date settleDate, String transType);
	
	List<SettleMerchantRecord> querySettleMerchantRecord(Map<String, Object> paraMap);

	/**
	 * 
	 * @方法说明：根据商户编码查询结算数据
	 * @author chenyanming
	 * @param merchantId
	 * @param date 
	 * @param status 
	 * @return
	 * @时间：2017年6月22日下午2:14:14
	 */
	List<SettleMerchantRecord> querySettleMerchantByMerchantId(String merchantId, String date, String status);

	List<String> queryAllSettleData(String start);
}