/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.heepay.rpc.tpds.service;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2017-02-16")
public class BankWQService {

  public interface Iface {

    public String bankWithdraw(String requestHeader, String requestBody) throws org.apache.thrift.TException;

    public String bankStatusQuery(String requestHeader, String requestBody) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void bankWithdraw(String requestHeader, String requestBody, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException;

    public void bankStatusQuery(String requestHeader, String requestBody, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public String bankWithdraw(String requestHeader, String requestBody) throws org.apache.thrift.TException
    {
      send_bankWithdraw(requestHeader, requestBody);
      return recv_bankWithdraw();
    }

    public void send_bankWithdraw(String requestHeader, String requestBody) throws org.apache.thrift.TException
    {
      bankWithdraw_args args = new bankWithdraw_args();
      args.setRequestHeader(requestHeader);
      args.setRequestBody(requestBody);
      sendBase("bankWithdraw", args);
    }

    public String recv_bankWithdraw() throws org.apache.thrift.TException
    {
      bankWithdraw_result result = new bankWithdraw_result();
      receiveBase(result, "bankWithdraw");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "bankWithdraw failed: unknown result");
    }

    public String bankStatusQuery(String requestHeader, String requestBody) throws org.apache.thrift.TException
    {
      send_bankStatusQuery(requestHeader, requestBody);
      return recv_bankStatusQuery();
    }

    public void send_bankStatusQuery(String requestHeader, String requestBody) throws org.apache.thrift.TException
    {
      bankStatusQuery_args args = new bankStatusQuery_args();
      args.setRequestHeader(requestHeader);
      args.setRequestBody(requestBody);
      sendBase("bankStatusQuery", args);
    }

    public String recv_bankStatusQuery() throws org.apache.thrift.TException
    {
      bankStatusQuery_result result = new bankStatusQuery_result();
      receiveBase(result, "bankStatusQuery");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "bankStatusQuery failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void bankWithdraw(String requestHeader, String requestBody, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException {
      checkReady();
      bankWithdraw_call method_call = new bankWithdraw_call(requestHeader, requestBody, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class bankWithdraw_call extends org.apache.thrift.async.TAsyncMethodCall {
      private String requestHeader;
      private String requestBody;
      public bankWithdraw_call(String requestHeader, String requestBody, org.apache.thrift.async.AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.requestHeader = requestHeader;
        this.requestBody = requestBody;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("bankWithdraw", org.apache.thrift.protocol.TMessageType.CALL, 0));
        bankWithdraw_args args = new bankWithdraw_args();
        args.setRequestHeader(requestHeader);
        args.setRequestBody(requestBody);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public String getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_bankWithdraw();
      }
    }

    public void bankStatusQuery(String requestHeader, String requestBody, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException {
      checkReady();
      bankStatusQuery_call method_call = new bankStatusQuery_call(requestHeader, requestBody, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class bankStatusQuery_call extends org.apache.thrift.async.TAsyncMethodCall {
      private String requestHeader;
      private String requestBody;
      public bankStatusQuery_call(String requestHeader, String requestBody, org.apache.thrift.async.AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.requestHeader = requestHeader;
        this.requestBody = requestBody;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("bankStatusQuery", org.apache.thrift.protocol.TMessageType.CALL, 0));
        bankStatusQuery_args args = new bankStatusQuery_args();
        args.setRequestHeader(requestHeader);
        args.setRequestBody(requestBody);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public String getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_bankStatusQuery();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("bankWithdraw", new bankWithdraw());
      processMap.put("bankStatusQuery", new bankStatusQuery());
      return processMap;
    }

    public static class bankWithdraw<I extends Iface> extends org.apache.thrift.ProcessFunction<I, bankWithdraw_args> {
      public bankWithdraw() {
        super("bankWithdraw");
      }

      public bankWithdraw_args getEmptyArgsInstance() {
        return new bankWithdraw_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public bankWithdraw_result getResult(I iface, bankWithdraw_args args) throws org.apache.thrift.TException {
        bankWithdraw_result result = new bankWithdraw_result();
        result.success = iface.bankWithdraw(args.requestHeader, args.requestBody);
        return result;
      }
    }

    public static class bankStatusQuery<I extends Iface> extends org.apache.thrift.ProcessFunction<I, bankStatusQuery_args> {
      public bankStatusQuery() {
        super("bankStatusQuery");
      }

      public bankStatusQuery_args getEmptyArgsInstance() {
        return new bankStatusQuery_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public bankStatusQuery_result getResult(I iface, bankStatusQuery_args args) throws org.apache.thrift.TException {
        bankStatusQuery_result result = new bankStatusQuery_result();
        result.success = iface.bankStatusQuery(args.requestHeader, args.requestBody);
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final Logger LOGGER = LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("bankWithdraw", new bankWithdraw());
      processMap.put("bankStatusQuery", new bankStatusQuery());
      return processMap;
    }

    public static class bankWithdraw<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, bankWithdraw_args, String> {
      public bankWithdraw() {
        super("bankWithdraw");
      }

      public bankWithdraw_args getEmptyArgsInstance() {
        return new bankWithdraw_args();
      }

      public AsyncMethodCallback<String> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<String>() { 
          public void onComplete(String o) {
            bankWithdraw_result result = new bankWithdraw_result();
            result.success = o;
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            bankWithdraw_result result = new bankWithdraw_result();
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, bankWithdraw_args args, org.apache.thrift.async.AsyncMethodCallback<String> resultHandler) throws TException {
        iface.bankWithdraw(args.requestHeader, args.requestBody,resultHandler);
      }
    }

    public static class bankStatusQuery<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, bankStatusQuery_args, String> {
      public bankStatusQuery() {
        super("bankStatusQuery");
      }

      public bankStatusQuery_args getEmptyArgsInstance() {
        return new bankStatusQuery_args();
      }

      public AsyncMethodCallback<String> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<String>() { 
          public void onComplete(String o) {
            bankStatusQuery_result result = new bankStatusQuery_result();
            result.success = o;
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            bankStatusQuery_result result = new bankStatusQuery_result();
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, bankStatusQuery_args args, org.apache.thrift.async.AsyncMethodCallback<String> resultHandler) throws TException {
        iface.bankStatusQuery(args.requestHeader, args.requestBody,resultHandler);
      }
    }

  }

  public static class bankWithdraw_args implements org.apache.thrift.TBase<bankWithdraw_args, bankWithdraw_args._Fields>, java.io.Serializable, Cloneable, Comparable<bankWithdraw_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("bankWithdraw_args");

    private static final org.apache.thrift.protocol.TField REQUEST_HEADER_FIELD_DESC = new org.apache.thrift.protocol.TField("requestHeader", org.apache.thrift.protocol.TType.STRING, (short)1);
    private static final org.apache.thrift.protocol.TField REQUEST_BODY_FIELD_DESC = new org.apache.thrift.protocol.TField("requestBody", org.apache.thrift.protocol.TType.STRING, (short)2);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new bankWithdraw_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new bankWithdraw_argsTupleSchemeFactory());
    }

    public String requestHeader; // required
    public String requestBody; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      REQUEST_HEADER((short)1, "requestHeader"),
      REQUEST_BODY((short)2, "requestBody");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // REQUEST_HEADER
            return REQUEST_HEADER;
          case 2: // REQUEST_BODY
            return REQUEST_BODY;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.REQUEST_HEADER, new org.apache.thrift.meta_data.FieldMetaData("requestHeader", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.REQUEST_BODY, new org.apache.thrift.meta_data.FieldMetaData("requestBody", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(bankWithdraw_args.class, metaDataMap);
    }

    public bankWithdraw_args() {
    }

    public bankWithdraw_args(
      String requestHeader,
      String requestBody)
    {
      this();
      this.requestHeader = requestHeader;
      this.requestBody = requestBody;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public bankWithdraw_args(bankWithdraw_args other) {
      if (other.isSetRequestHeader()) {
        this.requestHeader = other.requestHeader;
      }
      if (other.isSetRequestBody()) {
        this.requestBody = other.requestBody;
      }
    }

    public bankWithdraw_args deepCopy() {
      return new bankWithdraw_args(this);
    }

    @Override
    public void clear() {
      this.requestHeader = null;
      this.requestBody = null;
    }

    public String getRequestHeader() {
      return this.requestHeader;
    }

    public bankWithdraw_args setRequestHeader(String requestHeader) {
      this.requestHeader = requestHeader;
      return this;
    }

    public void unsetRequestHeader() {
      this.requestHeader = null;
    }

    /** Returns true if field requestHeader is set (has been assigned a value) and false otherwise */
    public boolean isSetRequestHeader() {
      return this.requestHeader != null;
    }

    public void setRequestHeaderIsSet(boolean value) {
      if (!value) {
        this.requestHeader = null;
      }
    }

    public String getRequestBody() {
      return this.requestBody;
    }

    public bankWithdraw_args setRequestBody(String requestBody) {
      this.requestBody = requestBody;
      return this;
    }

    public void unsetRequestBody() {
      this.requestBody = null;
    }

    /** Returns true if field requestBody is set (has been assigned a value) and false otherwise */
    public boolean isSetRequestBody() {
      return this.requestBody != null;
    }

    public void setRequestBodyIsSet(boolean value) {
      if (!value) {
        this.requestBody = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case REQUEST_HEADER:
        if (value == null) {
          unsetRequestHeader();
        } else {
          setRequestHeader((String)value);
        }
        break;

      case REQUEST_BODY:
        if (value == null) {
          unsetRequestBody();
        } else {
          setRequestBody((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case REQUEST_HEADER:
        return getRequestHeader();

      case REQUEST_BODY:
        return getRequestBody();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case REQUEST_HEADER:
        return isSetRequestHeader();
      case REQUEST_BODY:
        return isSetRequestBody();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof bankWithdraw_args)
        return this.equals((bankWithdraw_args)that);
      return false;
    }

    public boolean equals(bankWithdraw_args that) {
      if (that == null)
        return false;

      boolean this_present_requestHeader = true && this.isSetRequestHeader();
      boolean that_present_requestHeader = true && that.isSetRequestHeader();
      if (this_present_requestHeader || that_present_requestHeader) {
        if (!(this_present_requestHeader && that_present_requestHeader))
          return false;
        if (!this.requestHeader.equals(that.requestHeader))
          return false;
      }

      boolean this_present_requestBody = true && this.isSetRequestBody();
      boolean that_present_requestBody = true && that.isSetRequestBody();
      if (this_present_requestBody || that_present_requestBody) {
        if (!(this_present_requestBody && that_present_requestBody))
          return false;
        if (!this.requestBody.equals(that.requestBody))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_requestHeader = true && (isSetRequestHeader());
      list.add(present_requestHeader);
      if (present_requestHeader)
        list.add(requestHeader);

      boolean present_requestBody = true && (isSetRequestBody());
      list.add(present_requestBody);
      if (present_requestBody)
        list.add(requestBody);

      return list.hashCode();
    }

    @Override
    public int compareTo(bankWithdraw_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetRequestHeader()).compareTo(other.isSetRequestHeader());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetRequestHeader()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.requestHeader, other.requestHeader);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetRequestBody()).compareTo(other.isSetRequestBody());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetRequestBody()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.requestBody, other.requestBody);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("bankWithdraw_args(");
      boolean first = true;

      sb.append("requestHeader:");
      if (this.requestHeader == null) {
        sb.append("null");
      } else {
        sb.append(this.requestHeader);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("requestBody:");
      if (this.requestBody == null) {
        sb.append("null");
      } else {
        sb.append(this.requestBody);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class bankWithdraw_argsStandardSchemeFactory implements SchemeFactory {
      public bankWithdraw_argsStandardScheme getScheme() {
        return new bankWithdraw_argsStandardScheme();
      }
    }

    private static class bankWithdraw_argsStandardScheme extends StandardScheme<bankWithdraw_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, bankWithdraw_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // REQUEST_HEADER
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.requestHeader = iprot.readString();
                struct.setRequestHeaderIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // REQUEST_BODY
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.requestBody = iprot.readString();
                struct.setRequestBodyIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, bankWithdraw_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.requestHeader != null) {
          oprot.writeFieldBegin(REQUEST_HEADER_FIELD_DESC);
          oprot.writeString(struct.requestHeader);
          oprot.writeFieldEnd();
        }
        if (struct.requestBody != null) {
          oprot.writeFieldBegin(REQUEST_BODY_FIELD_DESC);
          oprot.writeString(struct.requestBody);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class bankWithdraw_argsTupleSchemeFactory implements SchemeFactory {
      public bankWithdraw_argsTupleScheme getScheme() {
        return new bankWithdraw_argsTupleScheme();
      }
    }

    private static class bankWithdraw_argsTupleScheme extends TupleScheme<bankWithdraw_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, bankWithdraw_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetRequestHeader()) {
          optionals.set(0);
        }
        if (struct.isSetRequestBody()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetRequestHeader()) {
          oprot.writeString(struct.requestHeader);
        }
        if (struct.isSetRequestBody()) {
          oprot.writeString(struct.requestBody);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, bankWithdraw_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.requestHeader = iprot.readString();
          struct.setRequestHeaderIsSet(true);
        }
        if (incoming.get(1)) {
          struct.requestBody = iprot.readString();
          struct.setRequestBodyIsSet(true);
        }
      }
    }

  }

  public static class bankWithdraw_result implements org.apache.thrift.TBase<bankWithdraw_result, bankWithdraw_result._Fields>, java.io.Serializable, Cloneable, Comparable<bankWithdraw_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("bankWithdraw_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRING, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new bankWithdraw_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new bankWithdraw_resultTupleSchemeFactory());
    }

    public String success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(bankWithdraw_result.class, metaDataMap);
    }

    public bankWithdraw_result() {
    }

    public bankWithdraw_result(
      String success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public bankWithdraw_result(bankWithdraw_result other) {
      if (other.isSetSuccess()) {
        this.success = other.success;
      }
    }

    public bankWithdraw_result deepCopy() {
      return new bankWithdraw_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public String getSuccess() {
      return this.success;
    }

    public bankWithdraw_result setSuccess(String success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof bankWithdraw_result)
        return this.equals((bankWithdraw_result)that);
      return false;
    }

    public boolean equals(bankWithdraw_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_success = true && (isSetSuccess());
      list.add(present_success);
      if (present_success)
        list.add(success);

      return list.hashCode();
    }

    @Override
    public int compareTo(bankWithdraw_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("bankWithdraw_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class bankWithdraw_resultStandardSchemeFactory implements SchemeFactory {
      public bankWithdraw_resultStandardScheme getScheme() {
        return new bankWithdraw_resultStandardScheme();
      }
    }

    private static class bankWithdraw_resultStandardScheme extends StandardScheme<bankWithdraw_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, bankWithdraw_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.success = iprot.readString();
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, bankWithdraw_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          oprot.writeString(struct.success);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class bankWithdraw_resultTupleSchemeFactory implements SchemeFactory {
      public bankWithdraw_resultTupleScheme getScheme() {
        return new bankWithdraw_resultTupleScheme();
      }
    }

    private static class bankWithdraw_resultTupleScheme extends TupleScheme<bankWithdraw_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, bankWithdraw_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          oprot.writeString(struct.success);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, bankWithdraw_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = iprot.readString();
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

  public static class bankStatusQuery_args implements org.apache.thrift.TBase<bankStatusQuery_args, bankStatusQuery_args._Fields>, java.io.Serializable, Cloneable, Comparable<bankStatusQuery_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("bankStatusQuery_args");

    private static final org.apache.thrift.protocol.TField REQUEST_HEADER_FIELD_DESC = new org.apache.thrift.protocol.TField("requestHeader", org.apache.thrift.protocol.TType.STRING, (short)1);
    private static final org.apache.thrift.protocol.TField REQUEST_BODY_FIELD_DESC = new org.apache.thrift.protocol.TField("requestBody", org.apache.thrift.protocol.TType.STRING, (short)2);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new bankStatusQuery_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new bankStatusQuery_argsTupleSchemeFactory());
    }

    public String requestHeader; // required
    public String requestBody; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      REQUEST_HEADER((short)1, "requestHeader"),
      REQUEST_BODY((short)2, "requestBody");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // REQUEST_HEADER
            return REQUEST_HEADER;
          case 2: // REQUEST_BODY
            return REQUEST_BODY;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.REQUEST_HEADER, new org.apache.thrift.meta_data.FieldMetaData("requestHeader", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.REQUEST_BODY, new org.apache.thrift.meta_data.FieldMetaData("requestBody", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(bankStatusQuery_args.class, metaDataMap);
    }

    public bankStatusQuery_args() {
    }

    public bankStatusQuery_args(
      String requestHeader,
      String requestBody)
    {
      this();
      this.requestHeader = requestHeader;
      this.requestBody = requestBody;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public bankStatusQuery_args(bankStatusQuery_args other) {
      if (other.isSetRequestHeader()) {
        this.requestHeader = other.requestHeader;
      }
      if (other.isSetRequestBody()) {
        this.requestBody = other.requestBody;
      }
    }

    public bankStatusQuery_args deepCopy() {
      return new bankStatusQuery_args(this);
    }

    @Override
    public void clear() {
      this.requestHeader = null;
      this.requestBody = null;
    }

    public String getRequestHeader() {
      return this.requestHeader;
    }

    public bankStatusQuery_args setRequestHeader(String requestHeader) {
      this.requestHeader = requestHeader;
      return this;
    }

    public void unsetRequestHeader() {
      this.requestHeader = null;
    }

    /** Returns true if field requestHeader is set (has been assigned a value) and false otherwise */
    public boolean isSetRequestHeader() {
      return this.requestHeader != null;
    }

    public void setRequestHeaderIsSet(boolean value) {
      if (!value) {
        this.requestHeader = null;
      }
    }

    public String getRequestBody() {
      return this.requestBody;
    }

    public bankStatusQuery_args setRequestBody(String requestBody) {
      this.requestBody = requestBody;
      return this;
    }

    public void unsetRequestBody() {
      this.requestBody = null;
    }

    /** Returns true if field requestBody is set (has been assigned a value) and false otherwise */
    public boolean isSetRequestBody() {
      return this.requestBody != null;
    }

    public void setRequestBodyIsSet(boolean value) {
      if (!value) {
        this.requestBody = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case REQUEST_HEADER:
        if (value == null) {
          unsetRequestHeader();
        } else {
          setRequestHeader((String)value);
        }
        break;

      case REQUEST_BODY:
        if (value == null) {
          unsetRequestBody();
        } else {
          setRequestBody((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case REQUEST_HEADER:
        return getRequestHeader();

      case REQUEST_BODY:
        return getRequestBody();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case REQUEST_HEADER:
        return isSetRequestHeader();
      case REQUEST_BODY:
        return isSetRequestBody();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof bankStatusQuery_args)
        return this.equals((bankStatusQuery_args)that);
      return false;
    }

    public boolean equals(bankStatusQuery_args that) {
      if (that == null)
        return false;

      boolean this_present_requestHeader = true && this.isSetRequestHeader();
      boolean that_present_requestHeader = true && that.isSetRequestHeader();
      if (this_present_requestHeader || that_present_requestHeader) {
        if (!(this_present_requestHeader && that_present_requestHeader))
          return false;
        if (!this.requestHeader.equals(that.requestHeader))
          return false;
      }

      boolean this_present_requestBody = true && this.isSetRequestBody();
      boolean that_present_requestBody = true && that.isSetRequestBody();
      if (this_present_requestBody || that_present_requestBody) {
        if (!(this_present_requestBody && that_present_requestBody))
          return false;
        if (!this.requestBody.equals(that.requestBody))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_requestHeader = true && (isSetRequestHeader());
      list.add(present_requestHeader);
      if (present_requestHeader)
        list.add(requestHeader);

      boolean present_requestBody = true && (isSetRequestBody());
      list.add(present_requestBody);
      if (present_requestBody)
        list.add(requestBody);

      return list.hashCode();
    }

    @Override
    public int compareTo(bankStatusQuery_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetRequestHeader()).compareTo(other.isSetRequestHeader());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetRequestHeader()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.requestHeader, other.requestHeader);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetRequestBody()).compareTo(other.isSetRequestBody());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetRequestBody()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.requestBody, other.requestBody);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("bankStatusQuery_args(");
      boolean first = true;

      sb.append("requestHeader:");
      if (this.requestHeader == null) {
        sb.append("null");
      } else {
        sb.append(this.requestHeader);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("requestBody:");
      if (this.requestBody == null) {
        sb.append("null");
      } else {
        sb.append(this.requestBody);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class bankStatusQuery_argsStandardSchemeFactory implements SchemeFactory {
      public bankStatusQuery_argsStandardScheme getScheme() {
        return new bankStatusQuery_argsStandardScheme();
      }
    }

    private static class bankStatusQuery_argsStandardScheme extends StandardScheme<bankStatusQuery_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, bankStatusQuery_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // REQUEST_HEADER
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.requestHeader = iprot.readString();
                struct.setRequestHeaderIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // REQUEST_BODY
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.requestBody = iprot.readString();
                struct.setRequestBodyIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, bankStatusQuery_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.requestHeader != null) {
          oprot.writeFieldBegin(REQUEST_HEADER_FIELD_DESC);
          oprot.writeString(struct.requestHeader);
          oprot.writeFieldEnd();
        }
        if (struct.requestBody != null) {
          oprot.writeFieldBegin(REQUEST_BODY_FIELD_DESC);
          oprot.writeString(struct.requestBody);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class bankStatusQuery_argsTupleSchemeFactory implements SchemeFactory {
      public bankStatusQuery_argsTupleScheme getScheme() {
        return new bankStatusQuery_argsTupleScheme();
      }
    }

    private static class bankStatusQuery_argsTupleScheme extends TupleScheme<bankStatusQuery_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, bankStatusQuery_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetRequestHeader()) {
          optionals.set(0);
        }
        if (struct.isSetRequestBody()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetRequestHeader()) {
          oprot.writeString(struct.requestHeader);
        }
        if (struct.isSetRequestBody()) {
          oprot.writeString(struct.requestBody);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, bankStatusQuery_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.requestHeader = iprot.readString();
          struct.setRequestHeaderIsSet(true);
        }
        if (incoming.get(1)) {
          struct.requestBody = iprot.readString();
          struct.setRequestBodyIsSet(true);
        }
      }
    }

  }

  public static class bankStatusQuery_result implements org.apache.thrift.TBase<bankStatusQuery_result, bankStatusQuery_result._Fields>, java.io.Serializable, Cloneable, Comparable<bankStatusQuery_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("bankStatusQuery_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRING, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new bankStatusQuery_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new bankStatusQuery_resultTupleSchemeFactory());
    }

    public String success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(bankStatusQuery_result.class, metaDataMap);
    }

    public bankStatusQuery_result() {
    }

    public bankStatusQuery_result(
      String success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public bankStatusQuery_result(bankStatusQuery_result other) {
      if (other.isSetSuccess()) {
        this.success = other.success;
      }
    }

    public bankStatusQuery_result deepCopy() {
      return new bankStatusQuery_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public String getSuccess() {
      return this.success;
    }

    public bankStatusQuery_result setSuccess(String success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof bankStatusQuery_result)
        return this.equals((bankStatusQuery_result)that);
      return false;
    }

    public boolean equals(bankStatusQuery_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_success = true && (isSetSuccess());
      list.add(present_success);
      if (present_success)
        list.add(success);

      return list.hashCode();
    }

    @Override
    public int compareTo(bankStatusQuery_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("bankStatusQuery_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class bankStatusQuery_resultStandardSchemeFactory implements SchemeFactory {
      public bankStatusQuery_resultStandardScheme getScheme() {
        return new bankStatusQuery_resultStandardScheme();
      }
    }

    private static class bankStatusQuery_resultStandardScheme extends StandardScheme<bankStatusQuery_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, bankStatusQuery_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.success = iprot.readString();
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, bankStatusQuery_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          oprot.writeString(struct.success);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class bankStatusQuery_resultTupleSchemeFactory implements SchemeFactory {
      public bankStatusQuery_resultTupleScheme getScheme() {
        return new bankStatusQuery_resultTupleScheme();
      }
    }

    private static class bankStatusQuery_resultTupleScheme extends TupleScheme<bankStatusQuery_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, bankStatusQuery_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          oprot.writeString(struct.success);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, bankStatusQuery_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = iprot.readString();
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

}
